---
- name: clone dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles }}"
    version: "{{ dotfiles_version }}"
  tags: never,test

- debug:
    msg: "not really cloning"

- name: collect topic configs
  block:
    - find:
        path: "{{ dotfiles }}"
        patterns: "config.yml"
        file_type: file
        recurse: yes
      register: find_results
      tags: never, modular
    - set_fact:
        configs: "{{ find_results.files | map(attribute='path') | list }}"
      tags: never, modular
    - include_vars: "{{ item }}"
      loop: "{{ configs }}"
      tags: never, modular
    # Already matched?
    # include_vars: "{{ item }}"
    #   with_fileglob:
    #     - "{{ dotfiles }}/config.yml"
    #   tags: ["never"]
    - set_fact:
        present_topics: "{{ q('dict', topics) | map(attribute='value') | list | flatten | selectattr('state', 'equalto', 'present') | list }}"
    - set_fact:
        disabled_topics: "{{ q('dict', topics) | map(attribute='value') | list | flatten | selectattr('state', 'equalto', 'disabled') | list }}"
    - set_fact:
        absent_topics: "{{ q('dict', topics) | map(attribute='value') | list | flatten | selectattr('state', 'equalto', 'absent') | list }}"

- name: user should have a dotfiles_data directory
  file:
    path: "{{ dotfiles_data }}"
    state: directory

- include_tasks: links.yml
  loop: "{{ present_topics }}"
  loop_control:
    loop_var: topic
